
services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d customer_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  mock:
    build: ./mock-server
    container_name: mock
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  pipeline:
    build: ./pipeline-service
    container_name: pipeline
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      mock:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/customer_db
      MOCK_SERVER_URL: http://mock:5000
